apiVersion: 1

datasources:
  - name: ClickHouse-JCT
    uid: P2A9C6B5D4E1F0A7
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      secure: false
      username: default
      defaultDatabase: default
      logs:
        defaultDatabase: default
        defaultTable: jct_events
        timeColumn: ingest_time
      traces:
        defaultDatabase: default
        defaultTable: jct_events
    editable: true

