# some comment
classes:
    included:
        - ^.*hell.*
    excluded:
        - .*HelloWorldLoop.*
processor:
    fullQualifiedClass: de.marcelsauer.profiler.processor.tcp.AsyncTcpStackProcessor
    tcpHost: localhost
    tcpPort: 9999
    tcpConnectTimeoutMillis: 1000
    tcpReconnectDelayMillis: 1000
    # true = report every captured stack event
    reportAllStacks: true
    # used in dedup mode (reportAllStacks: false)
    stackHashResetIntervalMillis: 300000

