input {
    udp {
        port => 9999
        codec => json
    }
    tcp {
        port => 9999
        codec => json_lines
    }
}

output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "jct-events-%{+YYYY.MM.dd}"
    }
}
